baseurl = "https://www.aishraj.com"
languageCode = "en-us"
title = "On Software and other things"
author = "Aishraj Dahal"
copyright = "&copy; Aishraj Dahal. All Rights Reserved."
canonifyurls = true

[params]
  #search_engine = true
  ga_api_key = "UA-20524803-3"
  twitter = "https://twitter.com/aishrajdahal"
  github = "https://github.com/aishraj"
  bio = "I'm Aish, I'm a full stack developer and a distributed systems geek. You can find on Twitter at @aishrajdahal"

[taxonomies]
  tag = "tags"
