baseurl = "https://www.aishraj.com"
languageCode = "en-us"
title = "Aishraj Dahal's homepage"
author = "Aishraj"
canonifyurls = true

[params]
  #search_engine = true
  google_analytics_id = "UA-20524803-3"
  mixpanel_id = "a13cc482f469efc9843382f068381967"
  twitter_username = "aishrajdahal"
  #disqus_shortname = ""

[taxonomies]
  tag = "tags"

