baseurl = "https://aishraj.github.io/"
languageCode = "en-us"
title = "Aishraj Dahal's homepage"
author = "Aishraj"
canonifyurls = true

[params]
  #search_engine = true
  google_analytics_id = "UA-20524803-3"
  twitter_username = "aishrajdahal"
  #disqus_shortname = ""

